// <auto-generated />
using System;
using MediCore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediCore.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811124256_AddPersonelModulleri")]
    partial class AddPersonelModulleri
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MediCore.API.Entities.Doktor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CalistigiBirim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GoreveBaslamaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UzmanlikAlani")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Doktorlar");
                });

            modelBuilder.Entity("MediCore.API.Entities.Duyuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnemliMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Duyurular");
                });

            modelBuilder.Entity("MediCore.API.Entities.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Oncelik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonelAdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("MediCore.API.Entities.Hasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlerjiBilgisi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CikisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("HastaNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HastaYakiniAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HastaYakiniTelefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hastalik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OdaNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YatakNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hastalar");
                });

            modelBuilder.Entity("MediCore.API.Entities.HastaIlac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dozaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HastaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IlacId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullanimSekli")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KullanimSikligi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UygulandiMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UygulanmaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HastaId");

                    b.HasIndex("IlacId");

                    b.ToTable("HastaIlaclari");
                });

            modelBuilder.Entity("MediCore.API.Entities.HastahaneSevk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoktorNotu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeriDonusNotu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GeriDonusTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("HastaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SevkEdenAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SevkEdenKullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SevkEdilenHastane")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SevkNedeni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SevkTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("SevkTipi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HastaId");

                    b.ToTable("HastahaneSevkleri");
                });

            modelBuilder.Entity("MediCore.API.Entities.HemsireNotu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HastaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Not")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HastaId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("HemsireNotlari");
                });

            modelBuilder.Entity("MediCore.API.Entities.Ilac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EtkenMadde")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KritikStokSeviyesi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UreticiFirma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ilaclar");
                });

            modelBuilder.Entity("MediCore.API.Entities.IlacStok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adet")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("IlacId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartiNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SonKullanmaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IlacId");

                    b.ToTable("IlacStoklari");
                });

            modelBuilder.Entity("MediCore.API.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("MediCore.API.Entities.Nobet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("TEXT");

                    b.Property<string>("HemsireAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HemsireSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HemsireTelefon")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NobetTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeslimNotu")
                        .HasColumnType("TEXT");

                    b.Property<string>("VardiyaTuru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nobetler");
                });

            modelBuilder.Entity("MediCore.API.Entities.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonNobetTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ToplamNot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vardiya")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("MediCore.API.Entities.VardiyaRaporu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eksiklikler")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GenelDurum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notlar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeslimAlan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeslimEden")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VardiyaRaporlari");
                });

            modelBuilder.Entity("MediCore.API.Entities.VitalBulgu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AtesC")
                        .HasColumnType("TEXT");

                    b.Property<int>("HastaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NabizBPM")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SaturasyonYuzdesi")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoluSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TansiyonDiyastol")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TansiyonSistol")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HastaId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("VitalBulgular");
                });

            modelBuilder.Entity("MediCore.API.Entities.HastaIlac", b =>
                {
                    b.HasOne("MediCore.API.Entities.Hasta", "Hasta")
                        .WithMany()
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.API.Entities.Ilac", "Ilac")
                        .WithMany()
                        .HasForeignKey("IlacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hasta");

                    b.Navigation("Ilac");
                });

            modelBuilder.Entity("MediCore.API.Entities.HastahaneSevk", b =>
                {
                    b.HasOne("MediCore.API.Entities.Hasta", "Hasta")
                        .WithMany()
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hasta");
                });

            modelBuilder.Entity("MediCore.API.Entities.HemsireNotu", b =>
                {
                    b.HasOne("MediCore.API.Entities.Hasta", "Hasta")
                        .WithMany()
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.API.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hasta");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("MediCore.API.Entities.IlacStok", b =>
                {
                    b.HasOne("MediCore.API.Entities.Ilac", "Ilac")
                        .WithMany()
                        .HasForeignKey("IlacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilac");
                });

            modelBuilder.Entity("MediCore.API.Entities.VitalBulgu", b =>
                {
                    b.HasOne("MediCore.API.Entities.Hasta", "Hasta")
                        .WithMany()
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.API.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hasta");

                    b.Navigation("Kullanici");
                });
#pragma warning restore 612, 618
        }
    }
}
