// <auto-generated />
using System;
using MediCore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediCore.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810122915_AddFullSchema")]
    partial class AddFullSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MediCore.API.Entities.Doktor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UzmanlikAlani")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Doktorlar");
                });

            modelBuilder.Entity("MediCore.API.Entities.Hasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlerjiBilgisi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CikisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("HastaNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HastaYakiniAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HastaYakiniTelefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hastalik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OdaNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YatakNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hastalar");
                });

            modelBuilder.Entity("MediCore.API.Entities.HastaIlac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dozaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HastaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IlacId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullanimSekli")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KullanimSikligi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UygulandiMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UygulanmaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HastaId");

                    b.HasIndex("IlacId");

                    b.ToTable("HastaIlaclari");
                });

            modelBuilder.Entity("MediCore.API.Entities.HemsireNotu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HastaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Not")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HastaId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("HemsireNotlari");
                });

            modelBuilder.Entity("MediCore.API.Entities.Ilac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EtkenMadde")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KritikStokSeviyesi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UreticiFirma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ilaclar");
                });

            modelBuilder.Entity("MediCore.API.Entities.IlacStok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adet")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("IlacId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartiNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SonKullanmaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IlacId");

                    b.ToTable("IlacStoklari");
                });

            modelBuilder.Entity("MediCore.API.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ahmet",
                            EPosta = "yonetici@medicore.com",
                            Rol = "Yonetici",
                            SifreHash = "$2a$11$hhsH2tzcnPpnTAJmJnitQOl8WmTnb8cpMnfictcF1VLdkObbJerKy",
                            Soyad = "Yönetici",
                            TcKimlikNo = "11111111111"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ayşe",
                            EPosta = "hemsire@medicore.com",
                            Rol = "Hemsire",
                            SifreHash = "$2a$11$hhsH2tzcnPpnTAJmJnitQOl8WmTnb8cpMnfictcF1VLdkObbJerKy",
                            Soyad = "Hemşire",
                            TcKimlikNo = "22222222222"
                        });
                });

            modelBuilder.Entity("MediCore.API.Entities.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoktorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HastaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notlar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RandevuTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoktorId");

                    b.HasIndex("HastaId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("MediCore.API.Entities.VitalBulgu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AtesC")
                        .HasColumnType("TEXT");

                    b.Property<int>("HastaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NabizBPM")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SaturasyonYuzdesi")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoluSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TansiyonDiyastol")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TansiyonSistol")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HastaId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("VitalBulgular");
                });

            modelBuilder.Entity("MediCore.API.Entities.HastaIlac", b =>
                {
                    b.HasOne("MediCore.API.Entities.Hasta", "Hasta")
                        .WithMany()
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.API.Entities.Ilac", "Ilac")
                        .WithMany()
                        .HasForeignKey("IlacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hasta");

                    b.Navigation("Ilac");
                });

            modelBuilder.Entity("MediCore.API.Entities.HemsireNotu", b =>
                {
                    b.HasOne("MediCore.API.Entities.Hasta", "Hasta")
                        .WithMany()
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.API.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hasta");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("MediCore.API.Entities.IlacStok", b =>
                {
                    b.HasOne("MediCore.API.Entities.Ilac", "Ilac")
                        .WithMany()
                        .HasForeignKey("IlacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilac");
                });

            modelBuilder.Entity("MediCore.API.Entities.Randevu", b =>
                {
                    b.HasOne("MediCore.API.Entities.Doktor", "Doktor")
                        .WithMany("Randevular")
                        .HasForeignKey("DoktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.API.Entities.Hasta", "Hasta")
                        .WithMany()
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doktor");

                    b.Navigation("Hasta");
                });

            modelBuilder.Entity("MediCore.API.Entities.VitalBulgu", b =>
                {
                    b.HasOne("MediCore.API.Entities.Hasta", "Hasta")
                        .WithMany()
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.API.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hasta");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("MediCore.API.Entities.Doktor", b =>
                {
                    b.Navigation("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
